name: flutter_hooks_lint
description: A lint package providing guidelines for using flutter_hooks in your Flutter widget!
version: 1.2.1
homepage: https://github.com/nikaera/flutter_hooks_lint
repository: https://github.com/nikaera/flutter_hooks_lint
documentation: https://github.com/nikaera/flutter_hooks_lint
issue_tracker: https://github.com/nikaera/flutter_hooks_lint/issues

topics:
  - lint

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  analyzer: ^7.0.0
  custom_lint_builder: ^0.7.3
  # path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
