name: flutter_hooks_lint_flutter_test
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.3
  custom_lint_core: ^0.7.1
  hooks_riverpod: ^2.4.10
  test: ^1.24.0
  flutter_hooks_lint:
    path: ../flutter_hooks_lint

dependency_overrides:
  flutter_hooks_lint:
    path: ../flutter_hooks_lint
